name: Deploy CloudFormation Stack

on:
  push:
    branches:
      - master
    paths:
      - '*'

jobs:
  deploy:
    name: Deploy to AWS
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Deploy CloudFormation stack
        run: |
          aws cloudformation deploy \
            --template-file cloudformation-template.yaml \
            --stack-name my-architecture-stack \
            --capabilities CAPABILITY_NAMED_IAM \
            --parameter-overrides \
              EC2KeyName=kjtest_keypair_since_2022_03_22 \
              DBUsername=admin \
              DBPassword=SuperSecret123 \
              DBInstanceClass=db.t3.micro \
              DBEngine=mysql \
              DBEngineVersion=8.0 \
              DBAllocatedStorage=20
